### ISSUE TITLE
destroyedBlocks requirement

### ISSUE THREAD

**Issue by FrinshHD** [FrinshHD/AnturniaQuests#11]

**Comment by FrinshHD** [comment]
**Example config:**
```yaml
requirements:
  destroyedBlocks:
    - material: DIRT
      amount: 2
    - material: STONE
      amount: 6
```
