### ISSUE TITLE
Allow completing npcs in a storyline with ignoring their order

### ISSUE THREAD

**Issue by FrinshHD** [FrinshHD/AnturniaQuests#14]

**Comment by FrinshHD** [comment]
Example:
```yaml
storyline1:
  friendlyName: Nice storyline name
  cooldown: 2
  maxCompletions: 4
  timeToComplete: 43
  npcs:
    - npcID: bob
      friendlyName: Bob
      actions:
        - message: "hi1"
          clickSound:
            sound: ENTITY_EXPERIENCE_ORB_PICKUP
            volume: 50
            pitch: 1
        - message: "hi2"
        - command: "give %player% emerald 1"
          delay: 20 #in ticks (one second is equal to 20 ticks)
    - npcID: bob1
      actions:
        - message: "hi3"
        - message: "hi4"
      group: bob-npc
    - npcID: bob2
      actions:
        - message: "hi5"
        - message: "hi6"
      group: bob-npc
    - npcID: bob3
      actions:
       - message: "hi7"
       - message: "hi8"
      group: bob-npc
    - npcID: jeff
      actions:
        - message: "h5"
          command: "give %player% diamond 2"
        - message: "thx"
    - npcID: bob
      actions:
        - message: "end"
```
