### ISSUE TITLE
Reach Location Quest Objective

### ISSUE THREAD

**Issue by iChasm03** [FrinshHD/AnturniaQuests#8]
A quest type that requires the player to reach a location, and when they reach the location, it either continues the storyline, or sends a message then continues the storyline.

**Comment by FrinshHD** [comment]
**Example:**
```yml
dev1:
  friendlyName: "&6Dev Quest"
  description: This quest is only for developing
  category: dev
  requirements:
    reachLocation:
      - world: world
        location1: [10, 10, 10]
        location2: [20, 20, 20]
  rewards:
    items:
      - material: DIAMOND
        amount: 1
```
