### ISSUE TITLE
placedBlocks requirement

### ISSUE THREAD

**Issue by FrinshHD** [FrinshHD/AnturniaQuests#9]

**Comment by FrinshHD** [comment]
![image](https://github.com/FrinshHD/AnturniaQuests/assets/62144694/6d89eeaa-84c6-4c9e-bec6-1ed444e379d9)

**Comment by FrinshHD** [comment]
**Configuration example:**
```yaml
requirements:
  placedBlocks:
    - material: DIRT
      amount: 2
      worlds:
        - world
    - material: STONE
      amount: 6
```
